# Site settings
title: Jinal's Coding
header-img: img/home-bg.png
email: jinal@google.com
copyright_name: ingend88
description: > # this means to ignore newlines until "baseurl:"
  My progress
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ingend88
learn_profile: ingend88
email_username: jinal@google.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
